[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["src/**"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]

[project]
name = "vibechecks"
version = "0.1.0"
authors = [
  { name="tjtanjin", email="cjtanjin@gmail.com" },
  { name="konglyyy", email="kongleyi99@gmail.com" },
]
description = "A python package that uses LLMs to insanity-check of if/while conditions for logic."
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/konglyyy/vibechecks"
Issues = "https://github.com/konglyyy/vibechecks/issues"